version: "3.8"
services:
  backend:
    build: ./backend
    container_name: devops-course-notes-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/notes.json:/app/notes.json
    restart: always

  frontend:
    build: ./frontend
    container_name: devops-course-notes-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
