      - name: SSH into VM and deploy containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_IP_ADDRESS }}
          username: ${{ secrets.VM_SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            docker pull polina0602/devops-course-frontend:latest
            docker pull polina0602/devops-course-backend:latest

            docker compose -f ~/docker-compose.yml down
            docker compose -f ~/docker-compose.yml up -d


